### ISSUE TITLE
Implementacion para logeo y registro en iOS

### ISSUE THREAD

**Issue by bchampi** [juniorUsca/get-things-done#10]
Se creará prototipos con la herramienta Figma para el Inicio de Sesión y Registro en iOS

**Comment by juniorUsca** [comment]
Esa tarea ya lo tomo @FiorelaHuarancca en https://github.com/juniorUsca/get-things-done/issues/8

**Comment by juniorUsca** [comment]
Se realizara algo adicional en el registro y login??

**Comment by bchampi** [comment]
Implementación del prototipo que realizará @FiorelaHuarancca, validación y registro de usuario en Firebase que realizará @Franco16021998, pero en aplicativo móvil para iOS con Swift
