### ISSUE TITLE
Implementación de un Calendario para mostrar tareas Reservadas por fechas.

### ISSUE THREAD

**Issue by Jcarita** [juniorUsca/get-things-done#101]
**Calendario**
- Se implementara un Calendario donde se pueda mostrar las tareas o fechas reservadas del usuario.
- Se utilizara un modulo para react el cual nos ayuda a marcar las tareas de un usuario en el calendario con un JSON.

**Comment by ayrton-taco22** [comment]
Buen issue Joseph
