### ISSUE TITLE
Bug en el microservicio de Inbox (Ruta para crear un nuevo inbox)

### ISSUE THREAD

**Issue by javierflores02** [juniorUsca/get-things-done#103]
Describe the bug
Se encontró un bug al momento de acceder a la ruta para crear un inbox (ruta: http://localhost:3001/api/inbox/1, método: Post), ya que al tratar de ingresar el ID de un usuario inexistente, se responde con estado 500 y se muestra un error en pantalla.

To Reproduce

1. Go to Postman
2. Set POST Method
3. Set the route: "http://localhost:3001/api/inbox/1000"
4. Set the body params
5. See error

Screenshots
![image](https://user-images.githubusercontent.com/68212504/122628911-ac4b3a00-d07e-11eb-9c1f-088b7a783da5.png)

Desktop (please complete the following information):
OS: Windows 10
Browser: Chrome

**Comment by ayrton-taco22** [comment]
Buena observacion Javier
