### ISSUE TITLE
feat(UI-Login-Registro): Uso de hooks y styled Js

### ISSUE THREAD

**Issue by wilsonturpo** [juniorUsca/get-things-done#11]
Se hará una mejora completa en la re estructuración para evitar colisiones de estilos, a través del uso de Styled js, y se modularizará el login y registro en sub componentes para mejorar el código y la reutilización.

**Comment by juniorUsca** [comment]
Esta muy bien, completalo y documenta como otros pueden continuar sobre el proyecto por favor
