### ISSUE TITLE
Mejoramiento del diseño del Login en Flutter y adición de información en el ReadMe

### ISSUE THREAD

**Issue by Nikols-Venegas** [juniorUsca/get-things-done#110]
Se mejorará el diseño del inicio de sesión en flutter. Se adicionará en el archivo ReadMe imágenes del inicio de sesión anterior y el implementado por último. Además se indicará algunos detalles de este diseño.

**Comment by Nikols-Venegas** [comment]
#112

**Comment by Nikols-Venegas** [comment]
#112 PULL REQUEST

**Comment by ayrton-taco22** [comment]
Buena idea Nikols!
