### ISSUE TITLE
Create Microservice with Node and Firebase - Crud INBOX

### ISSUE THREAD

**Issue by ale-drian** [juniorUsca/get-things-done#122]
Se va a crear un microservicio hecho en Node con conexion a Firebase como base de datos en tiempo real (Realtme Database),  
Metodos implementados:
api/new-user/ --> este se realiza conjuntamente con el microservicio de autenticacion con firebase (la implementacion se debe hacer en la aplicacion web), se recupera el identificador del usuario al registrarse y este mismo se usa para identificar a cada nodo de usuarios y agruparlos con sus respectivos inbox, calendar, next_actions, incubator, etc.
CRUD Inbox
- listar todos los inbox de un usuario 
- listar un inbox de un usuario 
- crear un nuevo inbox
- eliminar un inbox
- actualizar un inbox

**Comment by wilsonturpo** [comment]
Esta funcionalidad fue asignada a Jilmer Branco, quizá podrías replantear el issue :)

**Comment by ale-drian** [comment]
#127 Se ha implementado el servicio
