### ISSUE TITLE
agregar el uso de delete con flutter http 

### ISSUE THREAD

**Issue by NAVIXXX** [juniorUsca/get-things-done#126]
agregar el uso de delete con flutter http

**Comment by FiorelaHuarancca** [comment]
Genial @NAVIXXX comentanos si el uso de delete solo será para el inbox, tickler, calendar, nextactions, etc o solo para una de ellas?

**Comment by NAVIXXX** [comment]
@FiorelaHuarancca todas las peticiones http serán solo para una ya que para las demás serán casi iguales y será mejor así para que mas compañeros puedan participar.
