### ISSUE TITLE
Implementación de una entrada para depositar tareas a hacer (inbox).

### ISSUE THREAD

**Issue by xeduardox54** [juniorUsca/get-things-done#130]
**¿Tu solicitud de función está relacionada al problema? Describela a continuación.**
Al tratarse del método GTD, es necesario disponer de una entrada para depositar notas sobre tareas a hacer para sacarlas de nuestra mente. A esto se le conoce como inbox dentro del método GTD, y es una característica principal que debe estar en un proyecto como este.

**Describe the solution you'd like**
Lo que debería haber en la primera pantalla del aplicativo debe ser una libreta de notas que funcione como el inbox de la aplicación, en la cual podremos anotar tareas a hacer que vayan presentándose a lo largo del día.

**Describe alternatives you've considered**
Podría ser que en lugar de una libreta fuera una secuencia de instrucciones a seguir para generar una tarea mejor preparada, dado que sería asistida por el sistema, pero siento que eso haría el integrar tareas al inbox más pesado, y esto debe ser sencillo dado que debe ser una acción a la que recurrir fácilmente.

**Additional context**
Principalmente, es necesario requerir de un modelo que nos muestre como se verá esta pantalla en el aplicativo sin dejar de considerar las demás pantallas para las demás funcionalidades del aplicativo. 
Esta debe ser la primera pantalla que se ve cuando un usuario inicia sesión.

**Comment by juanvi159** [comment]
Perfecto, Realiza su documentación en README.md e impleméntalo

**Comment by LuisHuamani** [comment]
Excelente, sube la interfaz que propones

**Comment by FiorelaHuarancca** [comment]
Muy buena aporte @xeduardox54 ! recuerda tomar en cuenta el modelo entidad relación de GTD para no causar futuros conflictos.
