### ISSUE TITLE
Creación de un menu Drawer ( menu lateral deslizable) dentro de la aplicación Flutter

### ISSUE THREAD

**Issue by Franco16021998** [juniorUsca/get-things-done#167]
Creación de un menu desplegable lateral dentro de Flutter con diferentes opciones que realizará la aplicación

**Comment by FiorelaHuarancca** [comment]
Hola @Franco16021998  eso ya lo implementó @FabrizioAtiquipa . Podrías talvez revisarlo y ver si podrías aportar algo más con el menú lateral deslizable para que puedas realizarlo .
