### ISSUE TITLE
Vista de introductoria de la aplicacion.

### ISSUE THREAD

**Issue by Prieto-Mayca-A** [juniorUsca/get-things-done#243]
Una vista la cual permita dar soporte a los usuario que quizas no sean como usar la aplicacion, o sobre dudas y mejoras que se le podrian hacer.

**Comment by FiorelaHuarancca** [comment]
Hola @Prieto-Mayca-A ! es una parte interesante que aportará mucho al proyecto pero este ya a sido asignado a @DiegoPamo en el issue #236 . Talvez podrías añadir mejoras o cambios a tú issue.
