### ISSUE TITLE
Crear microservicio de una base de datos con MongoDB

### ISSUE THREAD

**Issue by RubenRodrigo** [juniorUsca/get-things-done#29]
Se desea crear una microservicio de la base de datos con NodeJS. Se planea que el microservicio se conecte directamente con la base de datos y exponga una API con los siguientes métodos: 
- list: Lista de elementos de una tabla (GET)
- get: Obtener un elemento de una tabla (GET)
- insert: Insertar elementos en una tabla (POST)
- update: Actualizar elementos de una tabla (PUT)
- query: Realizar una Query a la base de datos. (GET)
Se documentara su uso en un archivo README.md

**Comment by juniorUsca** [comment]
Agregale al microservicio de Alejandra conexión a mongoDB

https://github.com/juniorUsca/get-things-done/blob/main/microservice/apiNode/index.js
