### ISSUE TITLE
MODELO ENTIDAD RELACION

### ISSUE THREAD

**Issue by FiorelaHuarancca** [juniorUsca/get-things-done#31]

**Comment by FiorelaHuarancca** [comment]
En qué me sugiere usted para desarrollarlo? @juniorUsca

**Comment by juniorUsca** [comment]
En mysql Workbench

**Comment by wilsonturpo** [comment]
En SQL Server puedes realizar el diagrama y a partir del modelo te genera el código SQL para la ejecución, o creación del mismo de forma instantánea, de igual forma lo hace MySQL Workbech, así  mismo Oracle DataModeler también ofrece esas características, personalmente sugiero que uses una de esas tres y no solo las que te brindan el gráfico.

**Comment by bchampi** [comment]
Se podría usar DataGrip para mostrar gráficamente la estructura de la base de datos implementada y las relaciones entre los objetos de base de datos y otras funciones que brinda este IDE. Y para el modelado de entidad relación, podríamos usar las que sugiere @wilsonturpo, ya que SQL Server seria una muy buena opción para el diagrama y la inserción de datos.

**Comment by ale-drian** [comment]
Hola, tengo una propuesta de base de datos relacional, la hice en LucidChart para bocetar una estructura, si te parece podrías tomarlo en cuenta para la elaboración del diagrama.
![image](https://user-images.githubusercontent.com/79278185/122488910-20fd7600-cfa4-11eb-8047-eff987d93201.png)
