### ISSUE TITLE
Authentication with facebook using firebase

### ISSUE THREAD

**Issue by LuisHuamani** [juniorUsca/get-things-done#35]

**Comment by wilsonturpo** [comment]
Okey Luis, por si te sirve te dejo un tutorial de cómo agregar Firebase a Next Js:
https://www.youtube.com/watch?v=tmglaI4kZ9E

**Comment by wilsonturpo** [comment]
Luis, harás tanto la autenticación para el registro y login o solo uno? ¿Cuál?

**Comment by LuisHuamani** [comment]
Si hago ambos vale como 2 o solo como 1

**Comment by juniorUsca** [comment]
cuenta como uno, el login botón de login y registro deben funcionar igual

**Comment by LuisHuamani** [comment]
vale hago ambos profesor

**Comment by wilsonturpo** [comment]
perfecto!
