### ISSUE TITLE
Authentication with github using firebase

### ISSUE THREAD

**Issue by LuisHuamani** [juniorUsca/get-things-done#37]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wilsonturpo** [comment]
Perfecto Luis, mira, encontré un video del canal midudev donde se hace dicha funcionalidad justo con Firebase y github, te podría servir: 
https://www.youtube.com/watch?v=UlYGGCNFcWo&list=PLV8x_i1fqBw1VR86y4C72xMGJ8ifjBwJ6&index=2
