### ISSUE TITLE
Prototypes in Figma (v 98.13)

### ISSUE THREAD

**Issue by drandredev** [juniorUsca/get-things-done#4]
Se aplicará  principios fundamentales de UI/UX

En este ISSUE se irán agregando paulatinamente prototipos de diferentes vistas para posteriormente ser añadidas mediante código

Cualquier duda, modificación o sugerencia dejarla plasmada aquí

Idea inicial:

<img width="800" alt="Screen Shot 2021-06-14 at 18 30 27" src="https://user-images.githubusercontent.com/67886654/121971826-46d61100-cd3f-11eb-80b2-8608367d8ef4.png">

**Comment by juniorUsca** [comment]
Excelente iniciativa, agreguemos la mayor cantidad de prototipos para inspirar buenos diseños

**Comment by drandredev** [comment]
Podemos tomar como guía una de las aplicaciones líderes en el ámbito de organización

Todoist
https://todoist.com

Como podemos ver esa aplicación usa algo diferente a las demás, el uso de **TEMPLATES** por lo que deberemos generar varios **TEMPLATES** para que el usuario tenga libertad de escoger cual se acopla a su forma de trabajo

**Comment by drandredev** [comment]
@juniorUsca Profesor disculpe, como enlazo mi ISSUE con el pull request que acabo de realizar?
