### ISSUE TITLE
README Modification

### ISSUE THREAD

**Issue by drandredev** [juniorUsca/get-things-done#5]
Se cambiará el README colocando los pilares de nuestra aplicación, que es lo que buscamos, en que nos basamos y como puede cambiar el estilo de vida del usuario en su uso constante.

**Comment by juniorUsca** [comment]
Genial, sugiero que se use https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/

Aqui hay algunas plantillas en las que nos podemos basar
https://github.com/matiassingers/awesome-readme
