### ISSUE TITLE
Splash View for iOS 14.1+ - SwiftUI

### ISSUE THREAD

**Issue by drandredev** [juniorUsca/get-things-done#53]
Se creará el Splashview para dispositivos iOS.

 **Requisitos**

- iOS 14.1+
- Xcode
<img width="400" alt="image" src="https://user-images.githubusercontent.com/67886654/122142882-ebc31d80-ce15-11eb-9056-ec71fb016b64.png">
- Colocar la imagen "logo" en los Assets

**Comment by drandredev** [comment]
PD: En caso se necesite utilizar la versión animada se deberá utilizar la librería 

[https://github.com/SDWebImage/SDWebImageSwiftUI](https://github.com/SDWebImage/SDWebImageSwiftUI)

Utilizar la propiedad **AnimatedImage** y llamar al logo animado.

**Comment by wilsonturpo** [comment]
Al parecer usarás SwiftUI, me parece perfecto utilizar las últimas tecnologías :)
