### ISSUE TITLE
Library Suggestion

### ISSUE THREAD

**Issue by drandredev** [juniorUsca/get-things-done#6]
En este ISSUE se podrán hacer **sugerencias** acercas de distintas librerías que **ayudaran** a los desarrolladores de Frontend y Backend, cada librería deberá tener el **nombre**, **url** y pequeña **descripción** para ahorrar el tiempo.

Por ejemplo

(FRONTEND)
- Animate.css (https://animate.style). Librería para agregar animaciones mediante CSS de forma rápida y sencilla

**Comment by juniorUsca** [comment]
Seria bueno tambien ponerlo en la documentación del README.md
