### ISSUE TITLE
vista para el perfil de usuario 

### ISSUE THREAD

**Issue by joselazarinos** [juniorUsca/get-things-done#60]
una vista donde poder visualizar el perfil de un usuario como foto y datos personales

**Comment by wilsonturpo** [comment]
Que tal José, bríndanos más detalles, será un prototipo? una nueva característica funcional?

**Comment by joselazarinos** [comment]
será una nueva característica funcional aun que solo se encargara de mostrar nomas datos pro mientras para acceder a esta capaz se agregue una barra lateral
