### ISSUE TITLE
Nuevo proyecto para móviles en flutter

### ISSUE THREAD

**Issue by marimber123** [juniorUsca/get-things-done#63]
Se creara una aplicación en flutter con flutterfire para la autenticación mediante socialAuth y correo.

**Comment by ayrton-taco22** [comment]
Buen comienzo, pero te aconsejo que crees el proyecto como primer paso para que los demas que trabajen en flutter puedan utilizar tus mismos recursos y el mismo proyecto, o tengan un codigo base
