### ISSUE TITLE
DIseño de login para aplicación en flutter

### ISSUE THREAD

**Issue by Franco16021998** [juniorUsca/get-things-done#66]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ayrton-taco22** [comment]
Explica un poco mas como diseñaras el login en flutter

**Comment by Franco16021998** [comment]
Realizar la interfaz gráfica del login de la aplicación, solo diseño no funcionalidad usare las librerias  material de flutter y flutter_login
