### ISSUE TITLE
Diseño de HomePage en Flutter.

### ISSUE THREAD

**Issue by FabrizioAtiquipa** [juniorUsca/get-things-done#69]
Se realizara la vista inicial  la cual mostrara todas las tareas que tengo durante el día, esta mostrara la información una imagen la importancia y la hora la cual se realizara la tarea.

**Comment by wilsonturpo** [comment]
Perfecto Fabrizio, supongo que mientras tanto trabajarás con datos estáticos (no de una DB o API) :)
