### ISSUE TITLE
Microservice: Nodejs - CRUD de tareas con un array local

### ISSUE THREAD

**Issue by ale-drian** [juniorUsca/get-things-done#7]
Crear un microservicio del modulo de Tareas en NodeJS, API para listar, crear, actualizar, eliminar objetos desde un array local, es decir sin una base de datos definida

**Comment by juniorUsca** [comment]
Genial, para el microservicio crea una carpeta en la ruta principal del repositorio, no olvides documentarlo en el readme como levantar el proyecto
