### ISSUE TITLE
Creación de un nuevo proyecto Flutter

### ISSUE THREAD

**Issue by Nikols-Venegas** [juniorUsca/get-things-done#73]
Se creará un proyecto en Flutter, para poder tener nuestro proyecto en un dispositivo móvil. Y poder empezar a trabajar en este.
Se creará la estructura de carpetas que se tendrá en este proyecto.

**Comment by ayrton-taco22** [comment]
Excelente, no olvidar crear la estructura de carpetas necesaria para Flutter

**Comment by Nikols-Venegas** [comment]
#74 PULL REQUEST
