### ISSUE TITLE
Integracion del microservicio de NodeJs con MongoDB y Atlas

### ISSUE THREAD

**Issue by ale-drian** [juniorUsca/get-things-done#76]
Se va a conectar el microservicio de NodeJS a una base de datos en en Atlas MongoDB para tener la base de datos en la nube, la base de datos se va a basar la siguiente estructura:
![image](https://user-images.githubusercontent.com/79278185/122497717-78571280-cfb3-11eb-8e90-aaedc8d4881c.png)

**Comment by wilsonturpo** [comment]
Perfecto Alejandra, ten cuidado con subir tus credenciales de acceso a MongoAtlas :)
