### ISSUE TITLE
Mejorando el archivo Readme del proyecto de Flutter

### ISSUE THREAD

**Issue by Nikols-Venegas** [juniorUsca/get-things-done#81]
Se mejorará el archivo readme del proyecto creado en flutter. Donde se documentará la configuración, instalación y además se comentará sobre los Plugins: Flutter y Dart de Visual Studio Code, que nos ayuda a crear y correr nuestro proyectos con facilidad.

**Comment by wilsonturpo** [comment]
Perfecto Nikols, te dejo una guía que te puede ayudar a realizar un `README.md` interesante:
https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/

Aquí encontrarás varios proyectos que poseen un `README.md` interesante: 
https://github.com/matiassingers/awesome-readme

**Comment by Nikols-Venegas** [comment]
#89 PULL REQUEST
