### ISSUE TITLE
Bug en el microservicio de Inbox (Ruta para editar un único inbox de un usuario)

### ISSUE THREAD

**Issue by javierflores02** [juniorUsca/get-things-done#94]
Describe the bug
Se encontraron falencias al momento de acceder a la ruta para editar determinado inbox de un usuario, (ruta: http://localhost:3001/api/inbox/1/11, método: Patch), ya que al tratar de ingresar el ID de un usuario inexistente, se responde con estado 500 y se muestra un error en pantalla; en adición a ello, al ingresar el ID de un usuario que existe, pero un ID de un inbox inexistente, se obtiene una respuesta aparentemente satisfactoria (estado 200) por parte del servidor.

To Reproduce

**Error - ID de usuario inexistente**
1. Go to Postman
2. Set PATCH Method
3. Set the route: "http://localhost:3001/api/inbox/1000/1"
4. Set the body params
5. See error

**Error - ID de inbox inexistente**
1. Go to Postman
2. Set PATCH Method
3. Set the route: "http://localhost:3001/api/inbox/1/10000"
4. Set the body params
5. See the apparently satisfactory response

Screenshots
**Error - ID de usuario inexistente**
![image](https://user-images.githubusercontent.com/68212504/122618613-3500b080-d054-11eb-8e8d-29fd4167d07d.png)

**Error - ID de inbox inexistente**
![image](https://user-images.githubusercontent.com/68212504/122618770-8d37b280-d054-11eb-8dcd-dba4da168c36.png)

Desktop (please complete the following information):
OS: Windows 10
Browser: Chrome

**Comment by ayrton-taco22** [comment]
Genial observacion
