### ISSUE TITLE
refactorizar codigo de la aplicacion flutter

### ISSUE THREAD

**Issue by marimber123** [juniorUsca/get-things-done#95]
Se harán los cambios necesarios para que el login funcione y ademas quitar comentarios y funciones que no se usan.

**Comment by wilsonturpo** [comment]
Perfecto, entonces le darás funcionalidad al login con flutter, coméntanos de dónde consumirás los datos :)

**Comment by marimber123** [comment]
si, con firebase y la cuenta de google para darle funcionalidad ese boton del login con package que pusieron

**Comment by wilsonturpo** [comment]
Perfecto!

**Comment by marimber123** [comment]
me aceptas el ultimo pull request tengo otros 2 en cola...
